BNB_SYMBOL = 'BNB.BNB'
BUSD_SYMBOL = 'BNB.BUSD-BD1'
BUSD_TEST_SYMBOL = 'BNB.BUSD-BAF'
USDT_SYMBOL = 'BNB.USDT-6D8'
BTCB_SYMBOL = 'BNB.BTCB-1DE'
BTCB_TEST_SYMBOL = 'BNB.BTCB-101'
BTC_SYMBOL = 'BTC.BTC'
ETHB_SYMBOL = 'BNB.ETH-1C9'
ETHB_TEST_SYMBOL = 'BNB.ETH-D5B'
RUNE_SYMBOL = 'BNB.RUNE-B1A'
RUNE_SYMBOL_DET = 'RUNE-DET'
STABLE_COIN_POOLS = (BUSD_SYMBOL, USDT_SYMBOL, BUSD_TEST_SYMBOL)


def is_stable_coin(pool):
    return pool in STABLE_COIN_POOLS


class NetworkIdents:
    TESTNET_MULTICHAIN = 'testnet-multi'
    CHAOSNET_MULTICHAIN = 'chaosnet-multi'
    CHAOSNET_BEP2CHAIN = 'chaosnet-bep2'


THOR_DIVIDER = 100_000_000.0
THOR_DIVIDER_INV = 1.0 / THOR_DIVIDER
