FROM python:3.9-slim-buster as production

WORKDIR /app
ADD ./app/requirements.txt .

RUN pip install --no-cache-dir streamlit --no-dependencies

EXPOSE 8501

#CMD [ "python", "./dashboard.py", "/config/config.yaml" ]
CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.enableCORS=false", "--server.address=0.0.0.0", "/config/config.yaml" ]
