FROM python:3.12-slim as production

WORKDIR /app
ADD ../app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir discord.py --no-dependencies

CMD [ "python", "./web_api.py", "/config/config.yaml" ]
