FROM python:3.11-slim-buster as production

WORKDIR /app
ADD ../app/requirements.txt .

RUN apt-get update -y && \
    apt-get install git build-essential cmake pkg-config -y

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir streamlit

EXPOSE 8501

#CMD [ "python", "./dashboard.py", "/config/config.yaml" ]
CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.enableCORS=false", "--server.address=0.0.0.0", "/config/config.yaml" ]
